# Generated by Django 4.0.4 on 2022-04-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(help_text='Valores para efetuar a operação.', verbose_name='valores')),
                ('operation_type', models.CharField(choices=[('addition', 'adição'), ('subtraction', 'subtração'), ('division', 'divisão'), ('multiplication', 'multiplicação')], default='addition', max_length=20, verbose_name='Tipo de operação')),
                ('result', models.IntegerField(verbose_name='resultado')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='authentication.user', verbose_name='Usuário')),
            ],
        ),
    ]
