# Generated by Django 4.0.4 on 2022-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_operationhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhistory',
            name='values',
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='values_a',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='values_b',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
