# Generated by Django 4.0.4 on 2022-04-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_delete_user'),
        ('operations', '0005_remove_operationhistory_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='Usuário'),
        ),
    ]
